name:                hydra-tools
version:             0.1.0.0
github:              "malob/hydra-tools"
license:             BSD3
author:              "Malo Bourgon"
maintainer:          "mbourgon@gmail.com"
copyright:           "2022 Malo Bourgon"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/malob/hydra-tools#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - containers
  - regex-posix
  - scalpel
  - text
  - transformers

executables:
  hydra-tools:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hydra-tools
    - bytestring

# tests:
#   hydra-tools-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - hydra-tools
